name: CPU tests (Ubunutu x86_64)
on: [pull_request]
jobs:
  build:
    name: Build and test HPG-MxP
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
