name: CPU tests (Ubunutu x86_64)
on: [pull_request]
jobs:
  build:
    name: Build and test HPG-MxP
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MPI library
        run: sudo apt-get update && sudo apt-get install -y mpich
      - name: Configure CMake project
        run: cmake -DHPGMP_ENABLE_MPI=On -DHPGMP_BUILD_REFERENCE=On -B ${{github.workspace}}/build
      - name: Build project
        run: cmake --build ${{github.workspace}}/build
      - name: Run tests with CTest
        run: ctest --verbose --test-dir ${{github.workspace}}/build --output-on-failure
